FROM java:8
#FROM openjdk:8-jre
MAINTAINER Carlos A L M Guimaraes

RUN mkdir -p /ftp/dados

WORKDIR /app
COPY transportearquivogma-0.0.1.jar .

ENTRYPOINT ["java","-jar","transportearquivogma-0.0.1.jar"]
 




 


